name: Publish

on:
  release:
    types: [published]

jobs:
  unit-tests:
      name: unit tests
      runs-on: ubuntu-latest
      env:
        CI: true
      steps:
        - uses: actions/checkout@v2
        - uses: actions/cache@v1
          with:
            path: ~/.cache/yarn
            key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
            restore-keys: |
              ${{ runner.os }}-yarn-
        - name: install dependencies
          run: yarn
        - name: unit test
          run: |
            yarn test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: '@palmetto'
      - run: yarn install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}